USE [master]
GO

/****** Object:  Database [Cadmus]    Script Date: 07/01/2013 11:00:16 ******/
CREATE DATABASE [Cadmus] ON  PRIMARY 
( NAME = N'Cadmus', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Cadmus.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Cadmus_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Cadmus_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Cadmus] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cadmus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cadmus] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cadmus] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cadmus] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cadmus] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cadmus] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cadmus] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cadmus] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Cadmus] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cadmus] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cadmus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cadmus] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cadmus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cadmus] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cadmus] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cadmus] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cadmus] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cadmus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cadmus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cadmus] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cadmus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cadmus] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cadmus] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cadmus] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cadmus] SET  READ_WRITE 
GO

ALTER DATABASE [Cadmus] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Cadmus] SET  MULTI_USER 
GO

ALTER DATABASE [Cadmus] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cadmus] SET DB_CHAINING OFF 
GO


